fixtures:
    symlinks:
      exiscan: "#{source_dir}"
    forge_modules:
      concat: 'ripienaar/concat'
      postgresql: "example42/postgresql"
      puppi: "example42/puppi"
      stdlib: "puppetlabs/stdlib"
      tinydata: "example42/tinydata"
      # tp: "example42/tp"
    repositories:
      tp:
        repo: "https://github.com/DavidS/puppet-tp.git"
        branch: "default-names"
