name 'uniak-exiscan'
version '0.0.1'
author 'David Schmitt <david@dasz.at>; Markus Burger <markus.burger@uni-ak.ac.at>'
license 'Apache 2.0'
project_page 'https://github.com/DavidS/puppet-exiscan'
source 'https://github.com/DavidS/puppet-exiscan'
summary 'A complex exim configuration for smap and virus scanning'
dependency 'example42-exim', '>=2.0.13'
dependency 'example42/postgresql', '2.0.7'
dependency 'puppetlabs/stdlib', '4.1.0'
dependency 'example42/puppi', '2.0.8'
